version: '3.0'
networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: 192.168.188.0/24

services:

  mysql57:
    container_name: mysql57
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    volumes:
      - ${MYSQL_DIR}/data:/var/lib/mysql
      - ${MYSQL_DIR}/config:/etc/mysql/conf.d
    networks:
      backend:
        ipv4_address: 192.168.188.2

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ${MONGO_DIR}/data/db/:/data/db/
      - ${MONGO_DIR}/etc/mongod.conf:/etc/mongod.conf
      - ${MONGO_DIR}/data/log/:/data/log/
    networks:
      backend:
        ipv4_address: 192.168.188.3

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - ${REDIS_DIR}/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ${REDIS_DIR}/data/:/data/
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    networks:
      backend:
        ipv4_address: 192.168.188.4